language: objective-c
osx_image: xcode9
cache:
  bundler: true

bundler_args: --without documentation --without development --deployment --jobs=3 --retry=3

matrix:
  include:
    - env:
        - COMMAND=FASTLANE_ALL
      script:
        - scripts/travis_env_lint.sh
        - scripts/populate-dummy-secrets.sh
        - FASTLANE_SKIP_UPDATE_CHECK=true fastlane all
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f build/reports/coverage/xml/cobertura.xml
      after_failure:
        - scripts/print_simulator_crashlogs.sh
      deploy:
        local_dir: docs
        provider: pages
        skip_cleanup: true
        keep-history: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
          tags: true
    - env:
        - COMMAND=POD_LIB_LINT
      if: branch != master
      script:
        - pod lib lint

